/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
void config(void);
void delay_us(uint16_t us );
void delay_ms(uint16_t ms );
void TIM1_UP_IRQHandler();
int main(void)
{
	config();
	GPIOC->ODR |= GPIO_ODR_ODR13;
    /* Loop forever */
	while(1){

	}
}
void config(void){
	RCC->CR |= RCC_CR_HSEON;
	while(!(RCC->CR & RCC_CR_HSERDY) );
	RCC->CFGR |= RCC_CFGR_SW_HSE;
	while(!(RCC->CFGR & RCC_CFGR_SWS_HSE));
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV1;
	RCC->CFGR|= RCC_CFGR_PPRE2_DIV1;

	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;

	GPIOC->CRH &=~ GPIO_CRH_CNF13;

	GPIOC->CRH |= GPIO_CRH_MODE13;

	TIM1->ARR =0xff;
	TIM1->PSC =7500000-1;

	TIM1->DIER |= TIM_DIER_UIE;



	TIM1->CR1 |=TIM_CR1_CEN;

	while(! (TIM1->SR & TIM_SR_UIF ));
//	 //bat ngat
	NVIC_SetPriority(TIM1_UP_IRQn ,1);

	NVIC_EnableIRQ(TIM1_UP_IRQn );



}
void delay_us(uint16_t us ){
	TIM1->CNT=0;
	while(TIM1->CNT <us);

}
void delay_ms(uint16_t ms){

	for (uint16_t i=0; i<ms ;i++){
		delay_us(1000);
	}
}
void TIM1_UP_IRQHandler(){
//	GPIOC->ODR &=~ GPIO_ODR_ODR13;
//	if(GPIOC->ODR & GPIO_ODR_ODR13 ){
//		GPIOC->ODR &=~ GPIO_ODR_ODR13;
//	}
//	else{
//		GPIOC->ODR |= GPIO_ODR_ODR13;
//	}

}
